### PR TITLE
Updates seraphimserapis

### PR DESCRIPTION
**Pull request by SeraphimSerapis**
- Formatting via prettier
- Adds unique id to allow for customization in the UI: see https://github.com/martinhoess/zwift_hass/commit/ada6f4fbb42aec04965127e64c04dbcfca99319a%5C#diff-a4faf095abe257849c1bc6191ee23b9c9dc6aae6318abf8ae64fa1d52a5f46e9 for the original commit
- Renamed device_state_attributes to extra_state_attributes to match current requirements from the Home Assistant team (device_state_attributes got deprecated)

Tested with hassfest and works fine for my installation and addresses #30 and #29.

### CODE REVIEW

**Comment by snicker** [comment]
Looks good, sorry for not seeing this until now! I will likely be able to merge later (thank you for the formatting improvements as well)

one concern- I can't recall which version of Home Assistant switched from `device_state_attributes` to `extra_state_attributes`, but we either need to add both (and return the same values) temporarily, or at a minimum require a minimum version of HA in the manifest (and hacs.json). This is common practice for any breaking changes so users on older versions of HA cannot update to the latest version of the integration

**Comment by SeraphimSerapis** [comment]
Do you have a preference? I'm fine either way with a slight preference towards raising the minimum version required to run this component.

**Comment by snicker** [comment]
agreed, I am okay with that approach to raise minimum version.

**Comment by SeraphimSerapis** [comment]
I merged your changes/fixes and increased the min version as agreed. Let me know if there's anything else you'd like to see addressed/changed.

**Comment by snicker** [comment]
Thanks @SeraphimSerapis ! all merged now.

**Pull request merged**
